blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/AegisHttp/aegis/discussions
    about: Please ask questions or start discussions in our main repository Q&A forum.
